export const VALIDAR_SESION="VALIDAR_SESION"
export const VALIDAR_SESION_EXITO="VALIDAR_SESION_EXITO"
export const VALIDAR_SESION_ERROR="VALIDAR_SESION_ERROR"
export const INICIAR_SESION="INICIAR_SESION"
export const INICIAR_SESION_ERROR="INICIAR_SESION_ERROR"
export const REINICIAR_ERROR="REINICIAR_ERROR"
export const CERRAR_SESION="CERRAR_SESION"
export const REGISTRARSE="REGISTRARSE"
export const REGISTRARSE_ERROR="REGISTRARSE_ERROR"



//Productos
export const CARGAR_PRODUCTOS="CARGAR_PRODUCTOS"
export const CARGAR_CATEGORIAS="CARGAR_CATEGORIAS"